[2025-05-08T16:32:42.347-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-08T16:32:42.353-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: request_operation.modoOperacion manual__2025-05-08T21:32:36.510327+00:00 [queued]>
[2025-05-08T16:32:42.356-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: request_operation.modoOperacion manual__2025-05-08T21:32:36.510327+00:00 [queued]>
[2025-05-08T16:32:42.357-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-05-08T16:32:42.371-0500] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): modoOperacion> on 2025-05-08 21:32:36.510327+00:00
[2025-05-08T16:32:42.376-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'request_operation', 'modoOperacion', 'manual__2025-05-08T21:32:36.510327+00:00', '--job-id', '2530', '--raw', '--subdir', 'DAGS_FOLDER/operations.py', '--cfg-path', '/tmp/tmps1zsjjis']
[2025-05-08T16:32:42.378-0500] {standard_task_runner.py:105} INFO - Job 2530: Subtask modoOperacion
[2025-05-08T16:32:42.379-0500] {logging_mixin.py:190} WARNING - /home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=126473) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-08T16:32:42.379-0500] {standard_task_runner.py:72} INFO - Started process 126502 to run task
[2025-05-08T16:32:42.409-0500] {task_command.py:467} INFO - Running <TaskInstance: request_operation.modoOperacion manual__2025-05-08T21:32:36.510327+00:00 [running]> on host DESKTOP-0R7MK50.
[2025-05-08T16:32:42.460-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='request_operation' AIRFLOW_CTX_TASK_ID='modoOperacion' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T21:32:36.510327+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-08T21:32:36.510327+00:00'
[2025-05-08T16:32:42.461-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-08T16:32:47.285-0500] {logging_mixin.py:190} WARNING - /home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/urllib3/connectionpool.py:1097 InsecureRequestWarning: Unverified HTTPS request is being made to host 'auth.iqoption.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2025-05-08T16:32:47.468-0500] {timeout.py:68} ERROR - Process timed out, PID: 126502
[2025-05-08T16:32:47.471-0500] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 763, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/iqoptions_bot/dags/operations.py", line 18, in modoOperacion
    API = ConectionApi(gmail=gmail, password=password)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/iqoptions_bot/dags/utils/extraction.py", line 21, in __init__
    self.API.connect()
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/iqoptionapi/stable_api.py", line 103, in connect
    check, reason = self.api.connect()
                    ^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/iqoptionapi/api.py", line 865, in connect
    response = self.get_ssid()
               ^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/iqoptionapi/api.py", line 812, in get_ssid
    response = self.login(
               ^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/iqoptionapi/http/login.py", line 30, in __call__
    return self._post(data=data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/iqoptionapi/http/login.py", line 17, in _post
    return self.api.send_http_request_v2(method="POST", url="https://auth.iqoption.com/api/v2/login",data=data, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/iqoptionapi/api.py", line 240, in send_http_request_v2
    response = self.session.request(method=method,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/http/client.py", line 1423, in getresponse
    response.begin()
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/socket.py", line 707, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/ssl.py", line 1252, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/ssl.py", line 1104, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ares/anaconda3/envs/iqoptions_env/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: Timeout, PID: 126502
[2025-05-08T16:32:47.475-0500] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=request_operation, task_id=modoOperacion, run_id=manual__2025-05-08T21:32:36.510327+00:00, execution_date=20250508T213236, start_date=20250508T213242, end_date=20250508T213247
[2025-05-08T16:32:47.500-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-08T16:32:47.541-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 2
[2025-05-08T16:32:47.549-0500] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-08T16:32:47.549-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
